name: publish

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  THEGRAPH_STORE_POSTGRES_DIESEL_URL: "postgresql://postgres:postgres@localhost:5432/graph_node_test"
  
jobs:
  publish-graph-node-image:
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/go-ipfs:v0.10.0
        ports:
          - 5001:5001
        env:
          postgres_host: postgres
          postgres_user: graph-node
          postgres_pass: let-me-in
          postgres_db: graph-node
          ipfs: 'ipfs:5001'
          ethereum: 'mainnet:https://mainnet.infura.io/v3/bd6aa84b84904cfe9fce24aaafa89f56'
          GRAPH_LOG: info
      postgres:
        image: postgres
        env:
          POSTGRES_USER: graph-node
          POSTGRES_PASSWORD: let-me-in
          POSTGRES_DB: graph-node
          PGDATA: "/var/lib/postgresql/data"
          POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
        volumes:
          - ./data/postgres:/var/lib/postgresql/data:Z
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the graph node Docker image
        run: |
          docker build . --file docker/Dockerfile --tag ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
          docker run ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
          docker push ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
