name: publish

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  THEGRAPH_STORE_POSTGRES_DIESEL_URL: "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
  IPFS_URL: 'http://localhost:5001'

jobs:
  publish-graph-node-image:
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/kubo:v0.17.0
        ports:
          - 5001:5001
      postgres:
        image: postgres
        env:
          POSTGRES_USER: graph-node
          POSTGRES_PASSWORD: let-me-in
          POSTGRES_DB: graph-node
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Wait for services to be ready
        run: |
          until curl -s $IPFS_URL/api/v0/version && pg_isready -h localhost -p 5432; do
            echo "Waiting for IPFS and Postgres..."
            sleep 5
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the graph node Docker image
        run: |
          docker build . --file docker/Dockerfile --tag ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest \
            --build-arg IPFS_URL=${{ env.IPFS_URL }}
          docker run ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
          docker push ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
