name: publish

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  THEGRAPH_STORE_POSTGRES_DIESEL_URL: "postgresql://postgres:postgres@localhost:5432/graph_node_test"
  
jobs:
  publish-graph-node-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the graph node Docker image
        run: |
          docker build . --file docker/Dockerfile --tag ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
          docker run ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
          docker push ghcr.io/wolfgangtomas5/graph-node-gcr-demo:latest
